# Generated by Django 2.2 on 2019-05-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0002_auto_20190512_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='adoptado',
        ),
        migrations.AddField(
            model_name='animal',
            name='adotado_por',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='animal',
            name='criado_por',
            field=models.IntegerField(default=0),
        ),
    ]
