# Generated by Django 2.1.7 on 2019-05-14 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0003_profile_animal_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='animal_list',
        ),
    ]
