# Generated by Django 2.1.7 on 2019-05-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0004_remove_profile_animal_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='owner_id',
            field=models.IntegerField(default=0),
        ),
    ]
