# Generated by Django 2.1.7 on 2019-05-15 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0003_auto_20190514_1601'),
        ('animais', '0005_animal_owner_id'),
    ]

    operations = [
    ]
