# Generated by Django 2.2 on 2019-05-15 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0006_merge_20190515_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='owner_id',
        ),
    ]
